import { EnhancedTemplate } from '../types';

export const starterTemplates: EnhancedTemplate[] = [
  {
    id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    name: 'Weekly Route Service (Per-Unit Loop)',
    description: 'Standard service template with per-unit scanning and tracking',
    template_type: 'service',
    version: '1.0',
    is_default_for_type: true,
    is_active: true,
    sections: [
      {
        id: 'header',
        type: 'text_input',
        title: 'Job Header',
        description: 'Auto-filled from job data',
        fields: [
          { id: 'customer', type: 'text', label: 'Customer', auto: true },
          { id: 'site', type: 'text', label: 'Site Address', auto: true },
          { id: 'route_date', type: 'date', label: 'Route Date', auto: true },
          { id: 'tech', type: 'text', label: 'Technician', auto: true },
          { id: 'truck', type: 'text', label: 'Truck #', auto: true },
        ],
      },
      {
        id: 'per_unit',
        type: 'per_unit_loop',
        title: 'Per-Unit Service',
        description: 'Scan each unit and record service details',
        repeat_for_each: true,
        fields: [
          { id: 'unit_scan', type: 'qr_scan', label: 'Scan Unit ID', required: true },
          { id: 'gps', type: 'gps_lock', label: 'GPS Location', auto: true },
          { id: 'status', type: 'quick_status', label: 'Service Status', required: true, options: ['Cleaned & Restocked', 'Partial - Blocked', 'Not Serviced'] },
          { id: 'restock', type: 'restock_quick', label: 'Restock Items', options: ['Blue (oz)', 'Paper Rolls', 'Hand Sanitizer', 'Water (gal)'] },
          { id: 'condition', type: 'condition_toggles', label: 'Condition Flags', options: ['Tipped', 'Damage', 'Graffiti', 'Overfull', 'Blocked'] },
          { id: 'photos', type: 'photo_set', label: 'Photos', options: ['Before', 'After'], required_if: 'status != Cleaned & Restocked' },
          { id: 'notes', type: 'text_area', label: 'Notes', rows: 2 },
        ],
        auto_actions: {
          create_task_if: ['Not Serviced', 'Damage'],
          suggest_fee_if: ['Blocked', 'Tipped'],
        },
      },
      {
        id: 'exceptions',
        type: 'text_area',
        title: 'Exceptions & Tasks',
        description: 'Auto-generated from unit issues',
        fields: [
          { id: 'exceptions', type: 'text_area', label: 'Exception Summary', rows: 3, auto: true },
        ],
      },
      {
        id: 'consumables',
        type: 'text_input',
        title: 'Consumables Summary',
        description: 'Auto-totaled from all units',
        fields: [
          { id: 'total_blue', type: 'number', label: 'Total Blue (oz)', auto: true },
          { id: 'total_paper', type: 'number', label: 'Total Paper Rolls', auto: true },
          { id: 'total_sanitizer', type: 'number', label: 'Hand Sanitizer Refills', auto: true },
          { id: 'total_water', type: 'number', label: 'Total Water (gal)', auto: true },
        ],
      },
      {
        id: 'signoff',
        type: 'customer_signoff',
        title: 'Customer Sign-off',
        fields: [
          { id: 'name', type: 'text', label: 'Customer Name', required: true },
          { id: 'role', type: 'text', label: 'Role/Title' },
          { id: 'signature', type: 'signature', label: 'Signature', required: true },
          { id: 'timestamp', type: 'datetime', label: 'Signed At', auto: true },
          { id: 'gps', type: 'gps_lock', label: 'GPS', auto: true },
        ],
      },
    ],
    logic_rules: {
      per_unit_loop: true,
      auto_requirements: [],
      default_values: {},
      fee_suggestions: [],
    },
    permissions: {
      tech_editable_fields: ['*'],
      office_editable_fields: ['*', 'fees', 'notes'],
      internal_only_fields: ['gps', 'timestamp'],
    },
    output_config: {
      pdf_layout: 'summary_first',
      customer_pdf_fields: ['customer', 'site', 'route_date', 'status', 'photos', 'signature'],
      internal_pdf_fields: ['*'],
      photo_grid_columns: 2,
      show_brand_header: true,
    },
  },
  {
    id: '2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    name: 'Delivery & Setup',
    description: 'Unit delivery and site setup checklist',
    template_type: 'delivery',
    version: '1.0',
    is_default_for_type: true,
    is_active: true,
    sections: [
      {
        id: 'delivery_setup',
        type: 'delivery_setup',
        title: 'Delivery & Setup',
        fields: [
          { id: 'site_contact', type: 'text', label: 'Site Contact Name', required: true },
          { id: 'site_phone', type: 'text', label: 'Site Contact Phone', required: true },
          { id: 'unit_type', type: 'dropdown', label: 'Unit Type', required: true, options: ['Standard', 'ADA', 'Luxury'] },
          { id: 'unit_count', type: 'number', label: 'Quantity', required: true },
          { id: 'placement_gps', type: 'gps_lock', label: 'Placement GPS', auto: true },
          { id: 'placement_notes', type: 'text_area', label: 'Placement Description', rows: 2 },
          { id: 'surface', type: 'dropdown', label: 'Surface Type', options: ['Gravel', 'Grass', 'Asphalt', 'Concrete'] },
          { id: 'checklist', type: 'checklist', label: 'Setup Checklist', options: ['Door swings free', 'Vent unobstructed', 'Accessible path', 'Level placement'] },
          { id: 'photos', type: 'photo_set', label: 'Photos', options: ['Wide Shot', 'Door Side'], required: true },
          { id: 'signature', type: 'signature', label: 'Customer Acceptance', required: true },
        ],
      },
    ],
    logic_rules: {
      per_unit_loop: false,
      auto_requirements: [],
      default_values: {},
      fee_suggestions: [],
    },
    permissions: {
      tech_editable_fields: ['*'],
      office_editable_fields: ['*'],
      internal_only_fields: [],
    },
    output_config: {
      pdf_layout: 'summary_first',
      customer_pdf_fields: ['*'],
      internal_pdf_fields: ['*'],
      photo_grid_columns: 2,
      show_brand_header: true,
    },
  },
  {
    id: '3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    name: 'Event Service & Reconciliation',
    description: 'Event setup and unit count reconciliation',
    template_type: 'event',
    version: '1.0',
    is_default_for_type: false,
    is_active: true,
    sections: [
      {
        id: 'event_info',
        type: 'event_service',
        title: 'Event Information',
        fields: [
          { id: 'event_name', type: 'text', label: 'Event Name', required: true },
          { id: 'event_dates', type: 'date', label: 'Event Dates', required: true },
          { id: 'headcount', type: 'number', label: 'Expected Headcount' },
          { id: 'service_frequency', type: 'dropdown', label: 'Service Frequency', options: ['Daily', 'Twice Daily', 'As Needed'] },
          { id: 'layout_zones', type: 'text_area', label: 'Layout Zones/Rows', rows: 3 },
          { id: 'ada_count', type: 'number', label: 'ADA Units', required: true },
          { id: 'expected_count', type: 'number', label: 'Expected Total Units', required: true },
          { id: 'actual_count', type: 'number', label: 'Actual Units Serviced', required: true },
          { id: 'variance', type: 'number', label: 'Variance', auto: true },
        ],
      },
    ],
    logic_rules: {
      per_unit_loop: false,
      auto_requirements: [],
      default_values: {},
      fee_suggestions: [],
    },
    permissions: {
      tech_editable_fields: ['*'],
      office_editable_fields: ['*'],
      internal_only_fields: [],
    },
    output_config: {
      pdf_layout: 'summary_first',
      customer_pdf_fields: ['*'],
      internal_pdf_fields: ['*'],
      photo_grid_columns: 2,
      show_brand_header: true,
    },
  },
  {
    id: '4',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    name: 'Pickup / Removal',
    description: 'Unit pickup and site cleanup',
    template_type: 'pickup',
    version: '1.0',
    is_default_for_type: true,
    is_active: true,
    sections: [
      {
        id: 'pickup',
        type: 'pickup_removal',
        title: 'Pickup / Removal',
        fields: [
          { id: 'count_retrieved', type: 'number', label: 'Units Retrieved', required: true },
          { id: 'exceptions', type: 'text_area', label: 'Exceptions (missing/damaged)', rows: 2 },
          { id: 'site_clean', type: 'checklist', label: 'Site Cleanup', options: ['Area clean', 'No spills', 'No debris left'] },
          { id: 'photos', type: 'photo_set', label: 'Final Site Photos', options: ['Area Overview'] },
          { id: 'fees', type: 'text_area', label: 'Additional Fees', rows: 2 },
        ],
      },
    ],
    logic_rules: {
      per_unit_loop: false,
      auto_requirements: [],
      default_values: {},
      fee_suggestions: [],
    },
    permissions: {
      tech_editable_fields: ['*'],
      office_editable_fields: ['*'],
      internal_only_fields: [],
    },
    output_config: {
      pdf_layout: 'summary_first',
      customer_pdf_fields: ['*'],
      internal_pdf_fields: ['*'],
      photo_grid_columns: 2,
      show_brand_header: true,
    },
  },
  {
    id: '5',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    name: 'Repair Ticket',
    description: 'Unit repair and parts tracking',
    template_type: 'repair',
    version: '1.0',
    is_default_for_type: true,
    is_active: true,
    sections: [
      {
        id: 'repair',
        type: 'repair_damage',
        title: 'Repair Details',
        fields: [
          { id: 'issue_codes', type: 'multi_select', label: 'Issue Codes', required: true, options: ['Door', 'Roof', 'Seat', 'Lock', 'Vent', 'Base', 'Graffiti'] },
          { id: 'parts_used', type: 'parts_used', label: 'Parts Used', required: true },
          { id: 'labor_time', type: 'number', label: 'Labor Time (hours)', required: true },
          { id: 'photos', type: 'photo_set', label: 'Before/After Photos', options: ['Before', 'After'], required: true },
          { id: 'resolution', type: 'dropdown', label: 'Resolution Status', options: ['Fixed', 'Partial', 'Needs Follow-up'], required: true },
        ],
      },
    ],
    logic_rules: {
      per_unit_loop: false,
      auto_requirements: [],
      default_values: {},
      fee_suggestions: [],
    },
    permissions: {
      tech_editable_fields: ['*'],
      office_editable_fields: ['*'],
      internal_only_fields: [],
    },
    output_config: {
      pdf_layout: 'summary_first',
      customer_pdf_fields: ['issue_codes', 'resolution', 'photos'],
      internal_pdf_fields: ['*'],
      photo_grid_columns: 2,
      show_brand_header: true,
    },
  },
  {
    id: '6',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    name: 'Site Survey / Pre-Event Walkthrough',
    description: 'Initial site assessment before service',
    template_type: 'inspection',
    version: '1.0',
    is_default_for_type: true,
    is_active: true,
    sections: [
      {
        id: 'survey',
        type: 'compliance_safety',
        title: 'Site Survey',
        fields: [
          { id: 'site_contact', type: 'text', label: 'Site Contact', required: true },
          { id: 'access_notes', type: 'text_area', label: 'Access Notes', rows: 2 },
          { id: 'surface_type', type: 'dropdown', label: 'Surface Type', options: ['Gravel', 'Grass', 'Asphalt', 'Concrete', 'Dirt'] },
          { id: 'ada_accessible', type: 'checklist', label: 'ADA Requirements', options: ['Accessible path', 'Proper slope', 'Turning radius'] },
          { id: 'hazards', type: 'multi_select', label: 'Potential Hazards', options: ['Overhead lines', 'Soft ground', 'Slopes', 'Tight spaces'] },
          { id: 'photos', type: 'photo_set', label: 'Site Photos', options: ['Overview', 'Placement Area', 'Access Route'], required: true },
          { id: 'recommendations', type: 'text_area', label: 'Recommendations', rows: 3 },
        ],
      },
    ],
    logic_rules: {
      per_unit_loop: false,
      auto_requirements: [],
      default_values: {},
      fee_suggestions: [],
    },
    permissions: {
      tech_editable_fields: ['*'],
      office_editable_fields: ['*'],
      internal_only_fields: [],
    },
    output_config: {
      pdf_layout: 'summary_first',
      customer_pdf_fields: ['*'],
      internal_pdf_fields: ['*'],
      photo_grid_columns: 3,
      show_brand_header: true,
    },
  },
];
