-- Enable RLS and add policies for all remaining tables
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_task_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compliance_document_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_compliance_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

-- Add public access policies for all tables
CREATE POLICY "Public access" ON public.customers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.vehicles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.maintenance_task_types FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.compliance_document_types FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.vehicle_compliance_documents FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.invoices FOR ALL USING (true) WITH CHECK (true);

-- Enable RLS for tables that still need it
ALTER TABLE public.product_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quote_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_item_attributes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_service_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_damage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_load_capacities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_buttons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.terms_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consumable_bundle_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routine_maintenance_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_location_coordinates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consumable_location_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_consumables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_location_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_report_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.location_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_portal_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_interaction_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.communication_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consumable_bundles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.error_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_equipment_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.load_management_sync_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_settings ENABLE ROW LEVEL SECURITY;

-- Add public access policies for all remaining tables
CREATE POLICY "Public access" ON public.product_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.equipment_assignments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.job_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.quotes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.quote_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.service_tickets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.product_properties FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.product_item_attributes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.product_variations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.customer_service_locations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.stock_adjustments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.vehicle_assignments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.vehicle_damage_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.vehicle_load_capacities FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.invoice_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.purchase_order_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.saved_buttons FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.terms_templates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.customer_contacts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.consumable_bundle_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.routine_maintenance_services FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.service_location_coordinates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.consumable_location_stock FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.job_consumables FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.customer_segments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.product_location_stock FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.maintenance_report_attachments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.location_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.customer_portal_tokens FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.customer_interaction_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.communication_templates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.service_categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.consumable_bundles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.error_reports FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.job_equipment_assignments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.load_management_sync_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access" ON public.company_settings FOR ALL USING (true) WITH CHECK (true);