// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbqxyotasszslacozcey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImticXh5b3Rhc3N6c2xhY296Y2V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2Mjg1MzYsImV4cCI6MjA3NjIwNDUzNn0.rqn9o7C66aOqfDOg2QXdz5o2PKiVXERPQm9ufGMLSY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});